# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170731_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 2)),
        ),
    ]
