# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170811_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(null=True, upload_to='users_image/'),
        ),
    ]
